name: jupyter-flex
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip

  - pip:
      # Base Python deps
      - setuptools
      - setuptools-scm
      - pylint
      - flake8
      - black
      - isort
      - twine
      - wheel
      - pytest
      - pytest-cov

      # This project pip deps
      - notebook
      - jupyterlab
      - voila>=0.2.0,<0.3
      - nbconvert>=6.0.0,<7
      - nbclient>=0.4.0
      - ipywidgets
      - libsass
      - pytest-html
      - pytest-needle
      - pytest-base-url
      - pytest-selenium
      - pytest-tornasync
      - jupyter-flex==0.6.3
      - illusionist

      # Examples
      - numpy
      - pandas
      - scipy
      - matplotlib
      - scikit-learn
      - statsmodels
      - altair
      - plotly
      - bqplot
      - bokeh
      - jupyter_bokeh
      - qgrid
      - ipyleaflet
      - ipysheet
      - pandas-datareader
      - colorlover
      - vega_datasets

      # Docs
      - mkdocs
      - mkdocs-material
      - mkdocs-jupyter>=0.15.0
      - mkdocs-minify-plugin
      - pygments
      - pymdown-extensions
